"""
CodeFill Agent System Prompts
"""

from .chat_agent import (
    CHAT_AGENT_SYSTEM_PROMPT,
    TOPIC_ALIASES,
    DIFFICULTY_MAP,
    LEVEL_RECOMMENDATIONS
)

from .blank_problem_agent import (
    BLANK_PROBLEM_SYSTEM_PROMPT,
    BLANK_DIFFICULTY_CONFIG
)

from .puzzle_problem_agent import (
    PUZZLE_PROBLEM_SYSTEM_PROMPT,
    PUZZLE_DIFFICULTY_CONFIG
)

from .guided_problem_agent import (
    GUIDED_PROBLEM_SYSTEM_PROMPT,
    GUIDED_DIFFICULTY_CONFIG
)

from .code_gen_agent import (
    CODE_GEN_SYSTEM_PROMPT,
    LEVEL_TOPIC_RECOMMENDATIONS,
    TOPIC_REQUIRED_CONCEPTS
)

from .hint_agent import (
    HINT_AGENT_SYSTEM_PROMPT,
    HINT_LEVEL_CONFIG,
    PROBLEM_TYPE_HINT_FOCUS,
    ERROR_HINT_TEMPLATES
)

from .free_chat_agent import (
    FREE_CHAT_SYSTEM_PROMPT,
    INTENT_ACTION_MAP,
    CONTEXT_REQUIRED_INTENTS
)

from .analysis_agent import (
    ANALYSIS_SYSTEM_PROMPT
)

__all__ = [
    # Chat Agent
    "CHAT_AGENT_SYSTEM_PROMPT",
    "TOPIC_ALIASES",
    "DIFFICULTY_MAP",
    "LEVEL_RECOMMENDATIONS",
    # Blank Problem Agent
    "BLANK_PROBLEM_SYSTEM_PROMPT",
    "BLANK_DIFFICULTY_CONFIG",
    # Puzzle Problem Agent
    "PUZZLE_PROBLEM_SYSTEM_PROMPT",
    "PUZZLE_DIFFICULTY_CONFIG",
    # Guided Problem Agent
    "GUIDED_PROBLEM_SYSTEM_PROMPT",
    "GUIDED_DIFFICULTY_CONFIG",
    # Code Generation Agent
    "CODE_GEN_SYSTEM_PROMPT",
    "LEVEL_TOPIC_RECOMMENDATIONS",
    "TOPIC_REQUIRED_CONCEPTS",
    # Hint Agent
    "HINT_AGENT_SYSTEM_PROMPT",
    "HINT_LEVEL_CONFIG",
    "PROBLEM_TYPE_HINT_FOCUS",
    "ERROR_HINT_TEMPLATES",
    # Free Chat Agent
    "FREE_CHAT_SYSTEM_PROMPT",
    "INTENT_ACTION_MAP",
    "CONTEXT_REQUIRED_INTENTS",
    # Analysis Agent
    "ANALYSIS_SYSTEM_PROMPT",
]
